export {useMonacoSetup} from "./useMonacoSetup"
export {useDecorations} from "./useDecorations"
export {useEditorEvents} from "./useEditorEvents"
export {useTasmHoverProvider} from "./useTasmHoverProvider"
export {useTasmCodeLensProvider} from "./useTasmCodeLensProvider"
export {useFuncLanguageProviders} from "./useFuncLanguageProviders"
export {useFolding} from "./useFolding"

export type {SupportedLanguage} from "./useMonacoSetup"
export type {HighlightGroup, HighlightRange} from "./useDecorations"
