name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v5

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Node.js 22.x
        uses: actions/setup-node@v5
        with:
          node-version: 22.x
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --immutable --check-cache --check-resolutions

      - name: Check yarn dedupe
        run: yarn dedupe --check

      - name: Run prettier
        run: yarn run fmt:check

      - name: Run eslint
        run: yarn run lint:ts

      - name: Run stylelint
        run: yarn run lint:css

      - name: Build project
        run: yarn run build:all

      - name: Upload GitHub Pages artifact
        if: github.repository == 'ton-blockchain/TxTracer' && github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5.0.0
        with:
          path: dist

  deploy:
    name: Deploy docs
    if: github.repository == 'ton-blockchain/TxTracer' && github.ref == 'refs/heads/main'
    needs: [build]
    runs-on: ubuntu-latest

    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5.0.0
